# This is an example .tarreleaser.yml file with some sane defaults.
#dist: "./dist"
archive:
#  compression_level: 9
  wrap_in_directory: "myapp"
#  includes:
#    - ""
#    - "*.md"
  excludes:
    - ".git"
    - ".idea"

publish:

