dist: trusty
language: go
go: '1.12.x'
script:
  - make build
  - make test
  - "! go fmt ./... 2>&1 | read"
  - ./tarreleaser init --debug
  - ./tarreleaser --skip-publish --debug

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
